### ISSUE TITLE
2020.04.18 to-do

### ISSUE THREAD

**Issue by minie12** [catsavestheworld/catproject#11]
미니겜 계속 수정...
- [x] dust 나오는 위치 수정

- [x] 박스 클릭했을 때 아래로 움직이지 않기

- [x] 박스 클릭했을 때 컨베이어 위로 올라오게 변경하기

- [x] 피버타임 in&out 세부적으로 수정하기

- [ ] (optional) 튜브 움직일 때 "지이잉" 같은 기계 소리 내기
