### ISSUE TITLE
2020.03.21~2020.03.28 to-do

### ISSUE THREAD

**Issue by Heo-Seon** [catsavestheworld/catproject#7]
**[우선순위 1]** - 21~28일 이내로
- [x] 미니게임3 튜브 리소스 작업
- [x] 메인화면 UI(버튼/소지금액 표시 탭) 작업

**[우선순위 2]** - 28일 이후로도 계속해서 작업
- [x] 고양이 기본 스탠딩 추가(2종류)

**Comment by Heo-Seon** [comment]
03.28 추가(~04.04)
- [x] **일시정지, 메인화면 고양이(with 캣휠) 기획서 작성**
- [x] 캣휠고영이 그래픽
- [x] 돈 없을때의 안내메시지(박스) 그래픽 작업
